name: Bug Report
description: Report something that isn't working
labels: ["type:bug", "status:triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run command X
        2. See error Y

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Dashboard (Frontend)
        - Gateway API (Backend)
        - Intelligence (AI/ML)
        - FHIR Integration
        - PDF Processing
        - Other
