name: Feature Request
description: Suggest a new feature or enhancement
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?

  - type: input
    id: design-link
    attributes:
      label: Design Reference
      description: Link to architecture/design doc section (optional)
      placeholder: "docs/designs/some-design.md#section"
