using Gateway.API.Contracts;
using Gateway.API.Models;
using iText.Forms;
using iText.Kernel.Pdf;

namespace Gateway.API.Services;

/// <summary>
/// Uses iText to stamp PA form data onto PDF templates.
/// Falls back to generating a placeholder PDF if no template exists.
/// </summary>
public sealed class PdfFormStamper : IPdfFormStamper
{
    private readonly ILogger<PdfFormStamper> _logger;
    private readonly IWebHostEnvironment _environment;

    /// <summary>
    /// Initializes a new instance of the <see cref="PdfFormStamper"/> class.
    /// </summary>
    /// <param name="logger">Logger for diagnostic output.</param>
    /// <param name="environment">Web host environment for resolving content root path.</param>
    public PdfFormStamper(ILogger<PdfFormStamper> logger, IWebHostEnvironment environment)
    {
        _logger = logger;
        _environment = environment;
    }

    /// <inheritdoc />
    public async Task<byte[]> StampFormAsync(
        PAFormData formData,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Stamping PA form for patient {PatientName}", formData.PatientName);

        // Look for template in assets directory
        var templatePath = Path.Combine(
            _environment.ContentRootPath,
            "..", "..", "..", "..",
            "assets", "pdf-templates",
            "mri-lumbar-pa-form.pdf");

        // If template doesn't exist, generate a simple placeholder PDF
        if (!File.Exists(templatePath))
        {
            _logger.LogWarning("Template not found at {Path}, generating placeholder", templatePath);
            return await GeneratePlaceholderPdfAsync(formData, cancellationToken);
        }

        await using var outputStream = new MemoryStream();

        using (var pdfReader = new PdfReader(templatePath))
        using (var pdfWriter = new PdfWriter(outputStream))
        using (var pdfDoc = new PdfDocument(pdfReader, pdfWriter))
        {
            var form = PdfAcroForm.GetAcroForm(pdfDoc, true);

            // Map form fields using the field mappings from intelligence service
            foreach (var (fieldName, value) in formData.FieldMappings)
            {
                var field = form.GetField(fieldName);
                if (field is not null)
                {
                    field.SetValue(value);
                    _logger.LogDebug("Set field {FieldName} = {Value}", fieldName, value);
                }
                else
                {
                    _logger.LogWarning("Field {FieldName} not found in template", fieldName);
                }
            }

            // Flatten the form to prevent editing
            form.FlattenFields();
        }

        return outputStream.ToArray();
    }

    private Task<byte[]> GeneratePlaceholderPdfAsync(PAFormData formData, CancellationToken cancellationToken)
    {
        // Generate a simple PDF with the form data for demo purposes
        using var outputStream = new MemoryStream();
        using var writer = new PdfWriter(outputStream);
        using var pdf = new PdfDocument(writer);
        var document = new iText.Layout.Document(pdf);

        document.Add(new iText.Layout.Element.Paragraph("PRIOR AUTHORIZATION REQUEST")
            .SetFontSize(18)
            .SetBold());

        document.Add(new iText.Layout.Element.Paragraph($"Generated by AuthScript")
            .SetFontSize(10)
            .SetItalic());

        document.Add(new iText.Layout.Element.Paragraph("\n"));

        document.Add(new iText.Layout.Element.Paragraph("PATIENT INFORMATION")
            .SetFontSize(14)
            .SetBold());

        document.Add(new iText.Layout.Element.Paragraph($"Name: {formData.PatientName}"));
        document.Add(new iText.Layout.Element.Paragraph($"Date of Birth: {formData.PatientDob}"));
        document.Add(new iText.Layout.Element.Paragraph($"Member ID: {formData.MemberId}"));

        document.Add(new iText.Layout.Element.Paragraph("\n"));

        document.Add(new iText.Layout.Element.Paragraph("PROCEDURE INFORMATION")
            .SetFontSize(14)
            .SetBold());

        document.Add(new iText.Layout.Element.Paragraph($"Procedure Code: {formData.ProcedureCode}"));
        document.Add(new iText.Layout.Element.Paragraph($"Diagnosis Codes: {string.Join(", ", formData.DiagnosisCodes)}"));

        document.Add(new iText.Layout.Element.Paragraph("\n"));

        document.Add(new iText.Layout.Element.Paragraph("CLINICAL SUMMARY")
            .SetFontSize(14)
            .SetBold());

        document.Add(new iText.Layout.Element.Paragraph(formData.ClinicalSummary));

        document.Add(new iText.Layout.Element.Paragraph("\n"));

        document.Add(new iText.Layout.Element.Paragraph($"AI Recommendation: {formData.Recommendation}")
            .SetFontSize(12)
            .SetBold());

        document.Add(new iText.Layout.Element.Paragraph($"Confidence Score: {formData.ConfidenceScore:P0}"));

        document.Close();

        return Task.FromResult(outputStream.ToArray());
    }
}
