/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartLaunchRouteImport } from './routes/smart-launch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisTransactionIdRouteImport } from './routes/analysis.$transactionId'

const SmartLaunchRoute = SmartLaunchRouteImport.update({
  id: '/smart-launch',
  path: '/smart-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisTransactionIdRoute = AnalysisTransactionIdRouteImport.update({
  id: '/analysis/$transactionId',
  path: '/analysis/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/smart-launch': typeof SmartLaunchRoute
  '/analysis/$transactionId': typeof AnalysisTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/smart-launch': typeof SmartLaunchRoute
  '/analysis/$transactionId': typeof AnalysisTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/smart-launch': typeof SmartLaunchRoute
  '/analysis/$transactionId': typeof AnalysisTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/smart-launch' | '/analysis/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/smart-launch' | '/analysis/$transactionId'
  id: '__root__' | '/' | '/smart-launch' | '/analysis/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SmartLaunchRoute: typeof SmartLaunchRoute
  AnalysisTransactionIdRoute: typeof AnalysisTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-launch': {
      id: '/smart-launch'
      path: '/smart-launch'
      fullPath: '/smart-launch'
      preLoaderRoute: typeof SmartLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$transactionId': {
      id: '/analysis/$transactionId'
      path: '/analysis/$transactionId'
      fullPath: '/analysis/$transactionId'
      preLoaderRoute: typeof AnalysisTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SmartLaunchRoute: SmartLaunchRoute,
  AnalysisTransactionIdRoute: AnalysisTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
